clc; clear; close all;

% Load model
load('plant_model.mat', 'trainedNet');
net = trainedNet;

% ===== MAIN UI =====
fig = uifigure('Name', 'FarmAssist AI Demo', ...
    'Position', [500 100 520 680], ...
    'Color', [0.94 0.97 0.94]);

% Header
uilabel(fig, 'Text', '🌿 FarmAssist AI', ...
    'Position', [100 640 320 30], ...
    'FontSize', 20, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center');

% Button
btn = uibutton(fig, 'push', ...
    'Text', 'Upload Leaf Image', ...
    'FontSize',15,...
    'Position', [160 590 200 40], ...
    'BackgroundColor', [0.2 0.6 0.3], ...
    'FontColor', 'white', ...
    'FontWeight', 'bold');

% ===== LAYOUT =====
imgW = 200; imgH = 200; gap = 40;
leftX = 60; rightX = leftX + imgW + gap;
centerX = (520 - imgW)/2;

% ===== AXES =====
origAxes = uiaxes(fig, 'Position', [centerX 360 imgW imgH]);
origAxes.XTick = []; origAxes.YTick = [];

heatAxes = uiaxes(fig, 'Position', [rightX 360 imgW imgH], 'Visible', 'off');
heatAxes.XTick = []; heatAxes.YTick = [];

% ===== LABELS =====
origLabel = uilabel(fig, 'Text', 'Original Image', ...
    'Position', [leftX 560 imgW 25], ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 14, 'FontWeight', 'bold', ...
    'Visible', 'off');

uilabel(fig, ...
    'Text', 'AI-powered plant disease detection', ...
    'Position', [100 280 320 20], ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 11, ...
    'FontColor', [0.5 0.5 0.5]);

heatLabel = uilabel(fig, 'Text', 'AI Heatmap', ...
    'Position', [rightX 560 imgW 25], ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 14, 'FontWeight', 'bold', ...
    'Visible', 'off');

% ===== RESULT PANEL =====
shadow = uipanel(fig, ...
    'Position', [33 33 460 300], ...
    'BackgroundColor', [0.85 0.85 0.85], ...
    'BorderType', 'none',...
    'Visible', 'off');

resultPanel = uipanel(fig, ...
    'Position', [30 40 460 300], ...
    'BackgroundColor', [0.88 0.96 0.88], ...
    'FontSize', 15, ...
    'Title', 'AI Advisory', ...
    'ForegroundColor',[0.2 0.2 0.2], ...
    'Visible', 'off');

diseaseLabel = uilabel(resultPanel, ...
    'Position', [20 230 420 50], ...
    'FontSize', 14, ...
    'FontWeight', 'bold',...
    'HorizontalAlignment', 'left');

diseaseLabel.WordWrap = 'on';

confLabel = uilabel(resultPanel, ...
    'Position', [20 220 420 20], ...
    'FontSize', 13);

uilabel(resultPanel, ...
    'Position', [10 210 440 2], ...
    'BackgroundColor', [0.6 0.8 0.6]);

% ===== SEVERITY BAR =====
severityBg = uipanel(resultPanel, ...
    'Position', [20 180 420 20], ...
    'BackgroundColor', [0.92 0.92 0.92],...
    'BorderType','line');

severityFill = uipanel(resultPanel, ...
    'Position', [20 180 0 20], ...
    'BackgroundColor', [1 0.7 0.2]);

severityTextValue = uilabel(resultPanel, ...
    'Position', [20 180 420 20], ...
    'Text', '0%', ...
    'HorizontalAlignment', 'center', ...
    'FontWeight', 'bold');

resultPanel.UserData.severityTextValue = severityTextValue;
resultPanel.UserData.severityFill = severityFill;

solutionBox = uitextarea(resultPanel, ...
    'Position', [20 20 420 140], ...
    'FontSize', 13, ...
    'Editable', 'off');

% Button action
btn.ButtonPushedFcn = @(btn,event) predictImage(net, origAxes, heatAxes, ...
    origLabel, heatLabel, resultPanel, diseaseLabel, confLabel, solutionBox, shadow);

% ================= FUNCTION =================
function predictImage(net, origAxes, heatAxes, origLabel, heatLabel, ...
    resultPanel, diseaseLabel, confLabel, solutionBox, shadow)

    imgW = 200; imgH = 200; gap = 40;
    leftX = 60; rightX = leftX + imgW + gap;

    [file, path] = uigetfile({'*.jpg;*.png','Image Files (*.jpg, *.png)'});
    if file == 0, return; end

    drawnow;

    img = imread(fullfile(path, file));
    img_resized = imresize(img, [224 224]);

    % Heatmap
    [overlayImg, infectedPercent] = highlightDisease(img);

    % Layout shift
    origAxes.Position = [leftX 360 imgW imgH];
    heatAxes.Position = [rightX 360 imgW imgH];

    heatAxes.Visible = 'on';
    origLabel.Visible = 'on';
    heatLabel.Visible = 'on';

    cla(origAxes);
    imshow(img, 'Parent', origAxes, 'InitialMagnification', 'fit');
    axis(origAxes, 'off');

    cla(heatAxes);
    imshow(overlayImg, 'Parent', heatAxes, 'InitialMagnification', 'fit');
    axis(heatAxes, 'off');

    % ===== MODEL =====
    [label, scores] = classify(net, img_resized);
    confidence = min(max(scores), 0.98);

    % ===== CLEAN LABEL =====
    label_str = char(label);

    label_str = strrep(label_str,'___',' ');
    label_str = strrep(label_str,'__',' ');
    label_str = strrep(label_str,'_',' ');

    label_str = regexprep(label_str,'\s+',' ');
    label_str = strtrim(label_str);

    label_lower = lower(label_str);

    severity = getSeverity(infectedPercent);

    % ===== UPDATE SEVERITY BAR =====
    severityFill = resultPanel.UserData.severityFill;

    barWidth = 420 * (infectedPercent / 100);
    severityFill.Position = [20 180 barWidth 20];

    severityTextValue = resultPanel.UserData.severityTextValue;
    severityTextValue.Text = ['Severity: ', num2str(infectedPercent, '%.0f'), '%'];

    if infectedPercent < 20
        severityFill.BackgroundColor = [0.4 0.8 0.4];
    elseif infectedPercent < 50
        severityFill.BackgroundColor = [0.95 0.75 0.2];
    else
        severityFill.BackgroundColor = [0.9 0.4 0.4];
    end

    % ===== DISEASE SOLUTION =====
    solution = getDiseaseSolution(label_lower, severity);

    % ===== RESULT =====
    resultPanel.Visible = 'on';
    shadow.Visible = 'on';

    diseaseLabel.Text = sprintf('Disease: %s\nSeverity: %s | Affected: %.1f%%', ...
    label_str, severity, infectedPercent);

    confLabel.Text = ['Confidence: ', num2str(confidence*100, '%.2f'), '%'];

    [cost, days] = estimateTreatment(label_lower, infectedPercent);

    fullText = sprintf([ ...
    '%s\n\n', ...
    '💰 Estimated Cost: ₹%d\n', ...
    '⏳ Recovery Time: %d days'], ...
    solution, cost, days);

    solutionBox.Value = fullText;

end

% ===== HEATMAP =====
function [overlayImg, infectedPercent] = highlightDisease(img)

    hsvImg = rgb2hsv(img);
    H = hsvImg(:,:,1);
    V = hsvImg(:,:,3);

    mask = (H > 0.05 & H < 0.15) | (V < 0.4);
    mask = bwareaopen(mask, 50);

    infectedPercent = sum(mask(:)) / numel(mask) * 100;

    heatmap = uint8(255 * mat2gray(mask));
    coloredMap = ind2rgb(heatmap, jet(256));
    coloredMap = im2uint8(coloredMap);

    overlayImg = imlincomb(0.6, img, 0.4, coloredMap);

end

% ===== SEVERITY =====
function severity = getSeverity(percent)

    if percent < 20
        severity = 'LOW';
    elseif percent < 50
        severity = 'MEDIUM';
    else
        severity = 'HIGH';
    end

end

% ===== COST ESTIMATION =====
function [cost, days] = estimateTreatment(label, percent)

    if contains(label, 'healthy')
        cost = 0;
        days = 0;
        return;
    end

    baseCost = 200;
    baseDays = 5;

    factor = percent / 50;

    cost = round(baseCost * (1 + factor));
    days = round(baseDays * (1 + factor/2));

end

% ===== DISEASE SOLUTIONS =====
function solution = getDiseaseSolution(label, severity)

label = lower(strtrim(label));

if contains(label,'healthy')

    solution = sprintf([ ...
    '🌱 HEALTHY PLANT\n\n', ...
    '📌 Status:\n', ...
    'No visible disease symptoms detected.\n\n', ...
    '✅ Recommendations:\n', ...
    '- Continue regular watering\n', ...
    '- Ensure proper sunlight exposure\n', ...
    '- Monitor regularly\n\n', ...
    '🌿 Maintenance Tips:\n', ...
    '- Maintain soil health\n', ...
    '- Use balanced fertilizers\n\n', ...
    '🧠 Expert Tip:\n', ...
    'Preventive care is always best']);

elseif contains(label,'blight')

    solution = sprintf([ ...
    '🍂 BLIGHT DISEASE (%s)\n\n', ...
    '📌 Description:\n', ...
    'Fungal disease causing dark lesions and leaf damage.\n\n', ...
    '💊 Treatment:\n', ...
    '- Apply fungicide spray\n', ...
    '- Remove infected leaves\n', ...
    '- Avoid overhead watering\n\n', ...
    '⚠ Prevention:\n', ...
    '- Crop rotation\n', ...
    '- Maintain airflow\n\n', ...
    '🌿 Organic Methods:\n', ...
    '- Neem oil spray\n\n', ...
    '🧠 Expert Tip:\n', ...
    'Early treatment prevents spread'], severity);

elseif contains(label,'virus')

    solution = sprintf([ ...
    '🦠 VIRAL DISEASE (%s)\n\n', ...
    '📌 Description:\n', ...
    'Virus infection affecting leaf growth and color.\n\n', ...
    '💊 Treatment:\n', ...
    '- Remove infected plants\n', ...
    '- Control insect vectors\n\n', ...
    '⚠ Prevention:\n', ...
    '- Use healthy seeds\n', ...
    '- Disinfect tools\n\n', ...
    '🌿 Organic Methods:\n', ...
    '- Neem oil for insect control\n\n', ...
    '🧠 Expert Tip:\n', ...
    'Viruses spread quickly through insects'], severity);

elseif contains(label,'spot')

    solution = sprintf([ ...
    '🟤 LEAF SPOT DISEASE (%s)\n\n', ...
    '📌 Description:\n', ...
    'Disease causing dark spots on leaves.\n\n', ...
    '💊 Treatment:\n', ...
    '- Apply fungicide/bactericide\n', ...
    '- Remove infected leaves\n\n', ...
    '⚠ Prevention:\n', ...
    '- Avoid wet foliage\n', ...
    '- Improve spacing\n\n', ...
    '🌿 Organic Methods:\n', ...
    '- Baking soda spray\n\n', ...
    '🧠 Expert Tip:\n', ...
    'Monitor lower leaves frequently'], severity);

elseif contains(label,'mold')

    solution = sprintf([ ...
    '🌫 LEAF MOLD (%s)\n\n', ...
    '📌 Description:\n', ...
    'Fungal disease causing fuzzy growth and yellow patches.\n\n', ...
    '💊 Treatment:\n', ...
    '- Use fungicide spray\n', ...
    '- Remove affected leaves\n\n', ...
    '⚠ Prevention:\n', ...
    '- Reduce humidity\n', ...
    '- Improve airflow\n\n', ...
    '🌿 Organic Methods:\n', ...
    '- Milk spray treatment\n\n', ...
    '🧠 Expert Tip:\n', ...
    'Humidity control is essential'], severity);

elseif contains(label,'rust')

    solution = sprintf([ ...
    '🟠 RUST DISEASE (%s)\n\n', ...
    '📌 Description:\n', ...
    'Fungal disease causing orange rust-like patches.\n\n', ...
    '💊 Treatment:\n', ...
    '- Apply fungicides\n', ...
    '- Remove infected leaves\n\n', ...
    '⚠ Prevention:\n', ...
    '- Avoid overcrowding\n', ...
    '- Maintain ventilation\n\n', ...
    '🌿 Organic Methods:\n', ...
    '- Sulfur-based spray\n\n', ...
    '🧠 Expert Tip:\n', ...
    'Early control reduces spread'], severity);

else

    solution = sprintf([ ...
    '❓ UNKNOWN CONDITION\n\n', ...
    '📌 Issue:\n', ...
    'Disease information unavailable.\n\n', ...
    '⚠ Suggestions:\n', ...
    '- Upload clearer image\n', ...
    '- Avoid blurry or dark photos\n\n', ...
    '🧠 Expert Tip:\n', ...
    'Consult agricultural expert']);

end

end
